- hosts: kvm_host
  gather_facts: false
  tasks:
    - name: Set root_playbook_dir for later use
      ansible.builtin.set_fact:
        root_playbook_dir: "{{ playbook_dir }}"
        cacheable: true
  tags:
    - always

- hosts: kvm_host
  gather_facts: true
  tasks:
    - name: Set deployment directory for later use
      ansible.builtin.set_fact:
        deploy_dir: "{{ ansible_user_dir }}/ocp4-homelab"
        cacheable: true
  tags:
    - always

- ansible.builtin.import_playbook: playbooks/prepare-hypervisor.yaml
  tags:
    - prepare-hypervisor

- ansible.builtin.import_playbook: playbooks/prepare-vms.yaml
  tags:
    - prepare-vms

- ansible.builtin.import_playbook: playbooks/install-ocp.yaml
  tags:
    - install-ocp
